Update ci.yaml
colcon/ci pull request #12
Opened 2023-07-16 10:30 UTC by mosfet80

switch to  actions/checkout@v3 from v2
switch to  actions/setup-python@v4 from v2

2023-07-16 15:21 UTC, mjcarroll approved these changes

2023-07-31 22:46 UTC, cottsay requested changes

2023-07-31 22:46 UTC, cottsay commented on strategy.json
> +        "python": "3.7"
We need to continue testing on Python 3.6 because we support RHEL 8 in ROS 2 which uses it, despite being EOL.

2023-08-11 19:50 UTC, cottsay commented
CI failed due to a problem in colcon-core. Should be resolved once colcon/colcon-core#562 is merged.

2023-08-28 22:27 UTC, cottsay approved these changes

2023-08-28 22:28 UTC, merged